# Generated by Django 5.2.8 on 2025-11-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorydb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=40, null=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='Category')),
            ],
        ),
    ]
